# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d5793893c9b3fca1808dd241b7bece4d603ca5a1254f64e5e7ae9cc38fda99847826ca824801fc250e9ed952acd357a00bfe03040703c4c87f9fe2e04ef0938

test:
  secret_key_base: 28fbd259f447de30d0d2550ddffdcd1d0f91383473a0da378f6fc6d8967f89f41e3a7fbe4a46a9462bc2b28b90c8427782c322508b59efa7e73f9969e319ed63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
